#cloud-config
#disable_root: true
#timezone: Europe/Moscow
autoinstall:
apt:
  sources:
    mongodb:
      source: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1.4.11 (GNU/Linux)

        mQINBFrXrqYBEACscLj2qgPpHBCQtgW1Yh29Ddgv6jssyWLAYmj0qngFLKoQMMbt
        SNBZylIKxfS+pUD9J5xfRZwfZOmtMIOFVWS9tcpeQXsiwC126tRyoFCIpoTmH7+R
        8/FfPrCYyXLP+ftEZfRV60wTwr5drR0S5pVIST3oaXXGkHkFC35U++udUG2Tl4Cs
        OPSCp1tsK6UOTjHFDH8PnasImJgD37QC8OOMIJS0jCtDZywJW6OCdpIRbuTWPK3P
        P48NLwGUJHixhVCmOgPPu9kDAfG3wLxiN85S2UbaaSXsdA4fF4SSwWNHTIYAg0yT
        xGepVyW4lkfcvng4jva24rQ9j1cm1b7bWeOkMH1aAcSyFzKCeNCNxbVOYVrcWNP4
        zrSUvsTKhwX8rPFMq9LkcKirDL9bRILvn/24VU6NdJfGbRjR6+Q7ooj7hYKLXtO5
        q0Q4nhjigpTWIoU6jdfbM9YqpKSELNnkDRAU+bRYSrNaFuizYgDZQvcVT6gbq26f
        JbgihoeJogEfim3kqRRJ3EUhE+EaVijl9iLDKkpurod26P2QSq9RKSuOCeauPjQv
        3BIiEMXco8O3v8W1y4TbnSQ3d28W9pN28IgAhmN2EU2sKqWPzNeG0V+L6mE5pA4o
        nD3z3JRpxAUFw08+9LnLRZ4D1u54OrHADsU8UpYZJCm1xw6T0e4dlxW6rQARAQAB
        tDdNb25nb0RCIDQuMiBSZWxlYXNlIFNpZ25pbmcgS2V5IDxwYWNrYWdpbmdAbW9u
        Z29kYi5jb20+iQI+BBMBAgAoBQJa166mAhsDBQkJZgGABgsJCAcDAgYVCAIJCgsE
        FgIDAQIeAQIXgAAKCRBLfFSaBY+LaxdXEACJMvkgr3Nt2xme9/6brGMbrEy6mQn7
        DZP98DXuS0tWvO5vkEO5IfRIvzG3zA0pATSBDVA0BvGnebQrGXZZ7Xfh0gz+zxlt
        TXv4eCyb6T4gRJuuQSFPTyDnZ3MbPESqj0UpIALmcLDJ01nqvbNPKxx5r08XQOtE
        i44Kcwc1Px5cPcYP9nmpDNLZjz3gkTm+zBygdE9beP02qXq7WcyghFmQZoLBW53e
        TqNPnMrrm5+6vgq+r/ttyiYTo7Zw8MrifN5okevzB0JhhSAW9g+4ZOp1QYbV8u8V
        pksJQDOIaBWIw8zosIQJTCVyd4hOyl8Ib2s2R0/grT51RgLYCNbUG6WTpKGgYBtr
        Mng10gozyDrnA3B+RiDx5uq+dNzuuMXWMit2nbcdanXdKNkaPmC6WVeU0rG5K1Wz
        jQMDvAInTszLcqH6zfEsjCoXj0z8UwcC4jahFDNMDBk3OhjMSL+fnvIhW84nKVHf
        AWL5jjSQdkrM/M8QRpRqls5apuIYHQwo6Oyd2Nk0n9T/GOMJ1jilxiPw9ihusf+k
        DfU0JI7T8fgxIv/wHNXUg7FOaaDJIfgGlCPUgtsNUDZZ9lFq+Zc5H8Wff3LNo7Se
        2xnzzoy2e+C3tsxAmVUTs+q0lyIzEK24lf71cp074KVV7rIYBELYtO2hAlJYjXJU
        bscTTjCKLf9leA==
        =UXPP
        -----END PGP PUBLIC KEY BLOCK-----
  preserve_sources_list: true
repo_update: true
repo_upgrade: true


users:
    - default
    - name: yc-user
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      ssh-authorized-keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZnh8KlKzXEY/zUwttpo8KCn5nbeiXHbI5V0HR5c0ricFTL4xNqFyRhFtJTXNOlkV9IvPu5Gnrwt79VWoYJqHyeRl2nhWwmoO8hysuUemguNgox1OCUzRd/UF7Jsu94YlijLKPxF4esnlu54CdtQMG5eqZL7/71MbdEl4yLRmacJkIdy2OdNCu6bltSCh8HLE0tAC9GYVvS2uoxzfH9hw9xti1LON22vFw7JdheEN2xuUUgCb/qViRguJQW1ll3QgAeMtRU6M0lJDdPuEAhLHUL/3Nfdd3d9Ptt4UXYXmTabuVux370WXCFToIVVpviDq3Y7z8d2XUO+JdBJCE+R9L0c2FGq/rawdi5tQLNw4jmLXQlCd+sAcdIlz1ZakD03pRv74kmcD1NZRjr4PeCMm9pWd0QHPjWa3s4g8zSS62uczIc0KmdY4zrqYBwgr1CaKC9vAqrDXAToFS55u6GAb3BjTxeYX+aNbQHroXkhw++FQHnLXdw+bZM7EF0lUSYrs= appuser"

packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - mongodb
  - git

runcmd:
  - [ systemctl, enable, mongodb ]
  - 'git clone -b monolith https://github.com/express42/reddit.git'
  - [ cd, reddit]
  - [ bundle, install]
  - [puma, -d]
