#cloud-config
package_update: true
package_upgrade: true
packages:
 - git
runcmd:
 - git clone -b cloud-testapp https://github.com/Otus-DevOps-2022-02/ravaevay_infra.git
 - cd ravaevay_infra
 - ./install_ruby.sh
 - ./install_mongodb.sh
 - ./deploy.sh
