- name: Deploy application
  hosts: app
  tags: deploy-tag
  tasks:
  - name: Install git
    become: true
    apt:
      name: git
      state: present


  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith # <-- Указываем нужную ветку
    notify: reload puma 2

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: reload puma 2
    become: true
    systemd: name=puma state=restarted
