---
# tasks file for app
  - name: Add config for DB connection
    template:
      src: db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu
      mode: 0644


  - name: Add unit file for Puma
    copy:
      src: puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  - name: enable puma
    become: true
    systemd: name=puma enabled=yes
