- name: Configure app environment
  hosts: app
  become: true
  vars:
    db_host: 10.128.0.27 # <-- подставьте сюда ваш IP
  tags: app-tag
  tasks:
  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu
      mode: 0644


  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted

  - name: enable puma
    systemd: name=puma enabled=yes
