---
dependency:
  name: galaxy
driver:
  name: vmware
  vcenter_hostname: 192.168.224.83
  vcenter_username: root
  vcenter_password: secret
  validate_certs: false
  datacenter: VVO -DC
  #esxi_hostname: 192.168.224.83
  cluster: VVO-Cluster
  folder: /vm/test
  vm_username: vagrant
  vm_password: vagrant
  instance_os_type: linux # is possible only specify [linux or windows]
  # The below are possible parameters to be specified if using the windows template.
  #winrm_port: 5986 # is WinRM port
  #connection: winrm # is the connection type
  #winrm_transport: ntlm # is the authentication type
  #winrm_server_cert_validation: ignore # is the server certificate validation mode
  # The below list is possible to define DNS nameservers
  #dns_servers:
  #  - "8.8.8.8"
  #  - "8.8.4.4"
platforms:
  - name: instance # is an instance name
    template: generic/ubuntu1604 # is to be used as a template when cloning an instance
    #resource_pool: change me to resource pool
    #snapshot_src: change me to snapshot name # is a snapshot name to be possible specified if you want to use linked clone.
    hardware:
      num_cpus: 2 # is cpu number to be configured to an instance
      memory_mb: 2048 # is memory size(MB) to be configured to an instance
    networks:
      - name: Vlan_223 # is a port group to be assigned to an instance
        #ip: 100.64.0.2 # is ip address to be configured to an instance
        #netmask: 255.255.255.0 # is netmask to be configured to an instance
        #gateway: 100.64.0.1 # is gateway to be configured to an instance
    # The below are possible parameters to be specified if using the windows template.
    #customization:
    #  fullname: molecule # is the server owner name
    #  orgname: molecule # is the organization name
provisioner:
  name: ansible
verifier:
  name: ansible
